// VAR LET CONST
/**
 * DEFAULT PARAMETER
 * TEMPLATE STRING
 * ARROW FUNCTION
 * DESTRUCTURING AND SPREAD OPERATOR
 *   DAN PASHE OBJECT THAKLE DAN PASH E O OBJECT DITE HOBE
 * KEYS AND VALUES AND ENTRIES => object.entries
 * FOR OF AND FOR IN
 *
 */
